def disection(game_from_db, numero1):
    address_assignment = numero1
    address_assignment %= game_from_db.number_of_players
    game_from_db.dealer = game_from_db.players.split()[address_assignment]
    address_assignment += 1
    address_assignment %= game_from_db.number_of_players
    game_from_db.sb_name = game_from_db.players.split()[address_assignment]
    address_assignment += 1
    address_assignment %= game_from_db.number_of_players
    game_from_db.bb_name = game_from_db.players.split()[address_assignment]
    address_assignment += 1
    address_assignment %= game_from_db.number_of_players
    game_from_db.fa_name = game_from_db.players.split()[address_assignment]